spring:
  application:
    name: Spring-Security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users_agent
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: true
  config:
    import:
      optinal:
        file: .env

api:
    key:  ${API_KEY}
    url:  'https://api:anthropic:com/v1/messages'

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web : DEBUG
