ALTER TABLE user_profiles
   DROP COLUMN IF EXISTS age,
    DROP COLUMN IF EXISTS magic_place,
    DROP COLUMN IF EXISTS favorite_animal,
    ADD COLUMN IF NOT EXISTS location   VARCHAR(100),
    ADD COLUMN IF NOT EXISTS occupation VARCHAR(100),
    ADD COLUMN IF NOT EXISTS interests  VARCHAR(500);

ALTER TABLE tag
    ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT 'geral';